// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Quartz.Examples.AspNetCore.Database.Models;

namespace Quartz.Examples.AspNetCore.Database
{
    public partial class CRCTestContext : DbContext
    {
        public CRCTestContext()
        {
        }

        public CRCTestContext(DbContextOptions<CRCTestContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeExtraField> EmployeeExtraFields { get; set; }
        public virtual DbSet<EmployeePresence> EmployeePresences { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Employee>(entity =>
            {
                entity.ToTable("Employee");

                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("ID");

                entity.Property(e => e.CurrentDepartmentId).HasColumnName("CurrentDepartmentID");

                entity.Property(e => e.Firmname).HasMaxLength(50);

                entity.Property(e => e.Firstname).HasMaxLength(50);

                entity.Property(e => e.Language).HasMaxLength(5);

                entity.Property(e => e.Lastname).HasMaxLength(50);
            });

            modelBuilder.Entity<EmployeeExtraField>(entity =>
            {
                entity.HasKey(e => new { e.EmployeeId, e.Code });

                entity.ToTable("EmployeeExtraField");

                entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");

                entity.Property(e => e.Code).HasMaxLength(50);

                entity.HasOne(d => d.Employee)
                    .WithMany(p => p.EmployeeExtraFields)
                    .HasForeignKey(d => d.EmployeeId)
                    .HasConstraintName("FK_EmployeeExtraField_Employee");
            });

            modelBuilder.Entity<EmployeePresence>(entity =>
            {
                entity.HasKey(e => new { e.ResourceId, e.SiteId, e.DeviceId });

                entity.ToTable("EmployeePresence");

                entity.Property(e => e.ResourceId).HasColumnName("ResourceID");

                entity.Property(e => e.SiteId).HasColumnName("SiteID");

                entity.Property(e => e.DeviceId).HasColumnName("DeviceID");

                entity.Property(e => e.LastRegistrationDateTime).HasColumnType("datetime");

                entity.HasOne(d => d.Resource)
                    .WithMany(p => p.EmployeePresences)
                    .HasForeignKey(d => d.ResourceId)
                    .HasConstraintName("FK_EmployeePresence_Employee");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}