// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quartz.Examples.AspNetCore.Database.Models
{
    public partial class EmployeePresence
    {
        public int ResourceId { get; set; }
        public int SiteId { get; set; }
        public int DeviceId { get; set; }
        public DateTime? LastRegistrationDateTime { get; set; }

        public virtual Employee Resource { get; set; }
    }
}