// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quartz.Examples.AspNetCore.Database.Models
{
    public partial class Employee
    {
        public Employee()
        {
            EmployeeExtraFields = new HashSet<EmployeeExtraField>();
            EmployeePresences = new HashSet<EmployeePresence>();
        }

        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Firmname { get; set; }
        public string Language { get; set; }
        public int? CurrentDepartmentId { get; set; }

        public virtual ICollection<EmployeeExtraField> EmployeeExtraFields { get; set; }
        public virtual ICollection<EmployeePresence> EmployeePresences { get; set; }
    }
}