// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quartz.Examples.AspNetCore.Database.Models
{
    public partial class EmployeeExtraField
    {
        public int EmployeeId { get; set; }
        public string Code { get; set; }
        public string Value { get; set; }

        public virtual Employee Employee { get; set; }
    }
}